# Generated by Django 4.2.2 on 2023-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
                ('gps', models.CharField(blank=True, max_length=40, null=True)),
                ('application_status', models.BooleanField(default=False)),
            ],
        ),
    ]
